version: "3.7"
services:
    synchronizer:
        image: ethangraf/synchronizer
        build: .
        ports:
            - "2216:2216"
        volumes:
            - ./:/go/src/github.com/eagraf/synchronizer
    cloudworker:
        image: ethangraf/cloudworker
        depends_on:
            - synchronizer
        environment:
            - SYNCHRONIZER_IP=127.0.0.1:2216
            - CLOUDWORKER_IP=172.20.128.2
        network_mode: host
