FROM golang:1.13

WORKDIR /go/src/github.com/eagraf/synchronizer
COPY . .

RUN go get -d -v ./...
RUN go install -v ./...

RUN go build

EXPOSE 2216:2216

#ENTRYPOINT CompileDaemon -recursive=true -log-prefix=false -build="go build" -command="./synchronizer"
CMD ["synchronizer"]