// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dataserver.proto

package service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Contains info on jobs and workers assigned to this data server
type ReceiveScheduleRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceiveScheduleRequest) Reset()         { *m = ReceiveScheduleRequest{} }
func (m *ReceiveScheduleRequest) String() string { return proto.CompactTextString(m) }
func (*ReceiveScheduleRequest) ProtoMessage()    {}
func (*ReceiveScheduleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d248291538510d87, []int{0}
}

func (m *ReceiveScheduleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiveScheduleRequest.Unmarshal(m, b)
}
func (m *ReceiveScheduleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiveScheduleRequest.Marshal(b, m, deterministic)
}
func (m *ReceiveScheduleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiveScheduleRequest.Merge(m, src)
}
func (m *ReceiveScheduleRequest) XXX_Size() int {
	return xxx_messageInfo_ReceiveScheduleRequest.Size(m)
}
func (m *ReceiveScheduleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiveScheduleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiveScheduleRequest proto.InternalMessageInfo

type ReceiveScheduleRequest_Schedule struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceiveScheduleRequest_Schedule) Reset()         { *m = ReceiveScheduleRequest_Schedule{} }
func (m *ReceiveScheduleRequest_Schedule) String() string { return proto.CompactTextString(m) }
func (*ReceiveScheduleRequest_Schedule) ProtoMessage()    {}
func (*ReceiveScheduleRequest_Schedule) Descriptor() ([]byte, []int) {
	return fileDescriptor_d248291538510d87, []int{0, 0}
}

func (m *ReceiveScheduleRequest_Schedule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiveScheduleRequest_Schedule.Unmarshal(m, b)
}
func (m *ReceiveScheduleRequest_Schedule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiveScheduleRequest_Schedule.Marshal(b, m, deterministic)
}
func (m *ReceiveScheduleRequest_Schedule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiveScheduleRequest_Schedule.Merge(m, src)
}
func (m *ReceiveScheduleRequest_Schedule) XXX_Size() int {
	return xxx_messageInfo_ReceiveScheduleRequest_Schedule.Size(m)
}
func (m *ReceiveScheduleRequest_Schedule) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiveScheduleRequest_Schedule.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiveScheduleRequest_Schedule proto.InternalMessageInfo

type ReceiveScheduleRequest_Schedule_Job struct {
	JobUUID              string   `protobuf:"bytes,1,opt,name=JobUUID,proto3" json:"JobUUID,omitempty"`
	JobType              string   `protobuf:"bytes,2,opt,name=JobType,proto3" json:"JobType,omitempty"`
	TaskSize             int32    `protobuf:"varint,3,opt,name=TaskSize,proto3" json:"TaskSize,omitempty"`
	TaskNumber           int32    `protobuf:"varint,4,opt,name=TaskNumber,proto3" json:"TaskNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceiveScheduleRequest_Schedule_Job) Reset()         { *m = ReceiveScheduleRequest_Schedule_Job{} }
func (m *ReceiveScheduleRequest_Schedule_Job) String() string { return proto.CompactTextString(m) }
func (*ReceiveScheduleRequest_Schedule_Job) ProtoMessage()    {}
func (*ReceiveScheduleRequest_Schedule_Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_d248291538510d87, []int{0, 0, 0}
}

func (m *ReceiveScheduleRequest_Schedule_Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiveScheduleRequest_Schedule_Job.Unmarshal(m, b)
}
func (m *ReceiveScheduleRequest_Schedule_Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiveScheduleRequest_Schedule_Job.Marshal(b, m, deterministic)
}
func (m *ReceiveScheduleRequest_Schedule_Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiveScheduleRequest_Schedule_Job.Merge(m, src)
}
func (m *ReceiveScheduleRequest_Schedule_Job) XXX_Size() int {
	return xxx_messageInfo_ReceiveScheduleRequest_Schedule_Job.Size(m)
}
func (m *ReceiveScheduleRequest_Schedule_Job) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiveScheduleRequest_Schedule_Job.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiveScheduleRequest_Schedule_Job proto.InternalMessageInfo

func (m *ReceiveScheduleRequest_Schedule_Job) GetJobUUID() string {
	if m != nil {
		return m.JobUUID
	}
	return ""
}

func (m *ReceiveScheduleRequest_Schedule_Job) GetJobType() string {
	if m != nil {
		return m.JobType
	}
	return ""
}

func (m *ReceiveScheduleRequest_Schedule_Job) GetTaskSize() int32 {
	if m != nil {
		return m.TaskSize
	}
	return 0
}

func (m *ReceiveScheduleRequest_Schedule_Job) GetTaskNumber() int32 {
	if m != nil {
		return m.TaskNumber
	}
	return 0
}

type ReceiveScheduleRequest_Schedule_Worker struct {
	WorkerUUID           string                                         `protobuf:"bytes,1,opt,name=workerUUID,proto3" json:"workerUUID,omitempty"`
	DeviceType           string                                         `protobuf:"bytes,2,opt,name=deviceType,proto3" json:"deviceType,omitempty"`
	Tasks                []*ReceiveScheduleRequest_Schedule_Worker_Task `protobuf:"bytes,3,rep,name=tasks,proto3" json:"tasks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                       `json:"-"`
	XXX_unrecognized     []byte                                         `json:"-"`
	XXX_sizecache        int32                                          `json:"-"`
}

func (m *ReceiveScheduleRequest_Schedule_Worker) Reset() {
	*m = ReceiveScheduleRequest_Schedule_Worker{}
}
func (m *ReceiveScheduleRequest_Schedule_Worker) String() string { return proto.CompactTextString(m) }
func (*ReceiveScheduleRequest_Schedule_Worker) ProtoMessage()    {}
func (*ReceiveScheduleRequest_Schedule_Worker) Descriptor() ([]byte, []int) {
	return fileDescriptor_d248291538510d87, []int{0, 0, 1}
}

func (m *ReceiveScheduleRequest_Schedule_Worker) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiveScheduleRequest_Schedule_Worker.Unmarshal(m, b)
}
func (m *ReceiveScheduleRequest_Schedule_Worker) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiveScheduleRequest_Schedule_Worker.Marshal(b, m, deterministic)
}
func (m *ReceiveScheduleRequest_Schedule_Worker) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiveScheduleRequest_Schedule_Worker.Merge(m, src)
}
func (m *ReceiveScheduleRequest_Schedule_Worker) XXX_Size() int {
	return xxx_messageInfo_ReceiveScheduleRequest_Schedule_Worker.Size(m)
}
func (m *ReceiveScheduleRequest_Schedule_Worker) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiveScheduleRequest_Schedule_Worker.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiveScheduleRequest_Schedule_Worker proto.InternalMessageInfo

func (m *ReceiveScheduleRequest_Schedule_Worker) GetWorkerUUID() string {
	if m != nil {
		return m.WorkerUUID
	}
	return ""
}

func (m *ReceiveScheduleRequest_Schedule_Worker) GetDeviceType() string {
	if m != nil {
		return m.DeviceType
	}
	return ""
}

func (m *ReceiveScheduleRequest_Schedule_Worker) GetTasks() []*ReceiveScheduleRequest_Schedule_Worker_Task {
	if m != nil {
		return m.Tasks
	}
	return nil
}

type ReceiveScheduleRequest_Schedule_Worker_Task struct {
	JobUUID              string   `protobuf:"bytes,1,opt,name=JobUUID,proto3" json:"JobUUID,omitempty"`
	TaskIndex            int32    `protobuf:"varint,2,opt,name=TaskIndex,proto3" json:"TaskIndex,omitempty"`
	TaskSize             int32    `protobuf:"varint,3,opt,name=TaskSize,proto3" json:"TaskSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceiveScheduleRequest_Schedule_Worker_Task) Reset() {
	*m = ReceiveScheduleRequest_Schedule_Worker_Task{}
}
func (m *ReceiveScheduleRequest_Schedule_Worker_Task) String() string {
	return proto.CompactTextString(m)
}
func (*ReceiveScheduleRequest_Schedule_Worker_Task) ProtoMessage() {}
func (*ReceiveScheduleRequest_Schedule_Worker_Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_d248291538510d87, []int{0, 0, 1, 0}
}

func (m *ReceiveScheduleRequest_Schedule_Worker_Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiveScheduleRequest_Schedule_Worker_Task.Unmarshal(m, b)
}
func (m *ReceiveScheduleRequest_Schedule_Worker_Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiveScheduleRequest_Schedule_Worker_Task.Marshal(b, m, deterministic)
}
func (m *ReceiveScheduleRequest_Schedule_Worker_Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiveScheduleRequest_Schedule_Worker_Task.Merge(m, src)
}
func (m *ReceiveScheduleRequest_Schedule_Worker_Task) XXX_Size() int {
	return xxx_messageInfo_ReceiveScheduleRequest_Schedule_Worker_Task.Size(m)
}
func (m *ReceiveScheduleRequest_Schedule_Worker_Task) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiveScheduleRequest_Schedule_Worker_Task.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiveScheduleRequest_Schedule_Worker_Task proto.InternalMessageInfo

func (m *ReceiveScheduleRequest_Schedule_Worker_Task) GetJobUUID() string {
	if m != nil {
		return m.JobUUID
	}
	return ""
}

func (m *ReceiveScheduleRequest_Schedule_Worker_Task) GetTaskIndex() int32 {
	if m != nil {
		return m.TaskIndex
	}
	return 0
}

func (m *ReceiveScheduleRequest_Schedule_Worker_Task) GetTaskSize() int32 {
	if m != nil {
		return m.TaskSize
	}
	return 0
}

// Empty response for now
type ReceiveScheduleResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceiveScheduleResponse) Reset()         { *m = ReceiveScheduleResponse{} }
func (m *ReceiveScheduleResponse) String() string { return proto.CompactTextString(m) }
func (*ReceiveScheduleResponse) ProtoMessage()    {}
func (*ReceiveScheduleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d248291538510d87, []int{1}
}

func (m *ReceiveScheduleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiveScheduleResponse.Unmarshal(m, b)
}
func (m *ReceiveScheduleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiveScheduleResponse.Marshal(b, m, deterministic)
}
func (m *ReceiveScheduleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiveScheduleResponse.Merge(m, src)
}
func (m *ReceiveScheduleResponse) XXX_Size() int {
	return xxx_messageInfo_ReceiveScheduleResponse.Size(m)
}
func (m *ReceiveScheduleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiveScheduleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiveScheduleResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ReceiveScheduleRequest)(nil), "dataserverservice.ReceiveScheduleRequest")
	proto.RegisterType((*ReceiveScheduleRequest_Schedule)(nil), "dataserverservice.ReceiveScheduleRequest.Schedule")
	proto.RegisterType((*ReceiveScheduleRequest_Schedule_Job)(nil), "dataserverservice.ReceiveScheduleRequest.Schedule.Job")
	proto.RegisterType((*ReceiveScheduleRequest_Schedule_Worker)(nil), "dataserverservice.ReceiveScheduleRequest.Schedule.Worker")
	proto.RegisterType((*ReceiveScheduleRequest_Schedule_Worker_Task)(nil), "dataserverservice.ReceiveScheduleRequest.Schedule.Worker.Task")
	proto.RegisterType((*ReceiveScheduleResponse)(nil), "dataserverservice.ReceiveScheduleResponse")
}

func init() {
	proto.RegisterFile("dataserver.proto", fileDescriptor_d248291538510d87)
}

var fileDescriptor_d248291538510d87 = []byte{
	// 353 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xb1, 0x4f, 0xc2, 0x40,
	0x14, 0xc6, 0x2d, 0x05, 0x84, 0xe7, 0xa0, 0xdc, 0xa0, 0xb5, 0x31, 0x86, 0x30, 0x10, 0x74, 0x38,
	0x12, 0xdc, 0x1d, 0x08, 0x0b, 0x0c, 0xc6, 0xb4, 0x10, 0x13, 0xb6, 0x6b, 0xfb, 0x84, 0x8a, 0xf4,
	0xf0, 0xae, 0x45, 0x61, 0xf1, 0xef, 0xf0, 0x5f, 0x75, 0x30, 0xe6, 0xda, 0x02, 0x8d, 0x35, 0x84,
	0xa5, 0xb9, 0xef, 0x7b, 0xef, 0xdd, 0xfd, 0xde, 0x97, 0xc2, 0x99, 0xc7, 0x42, 0x26, 0x51, 0x2c,
	0x51, 0xd0, 0x85, 0xe0, 0x21, 0x27, 0xb5, 0x9d, 0xa3, 0xbe, 0xbe, 0x8b, 0x8d, 0x2f, 0x1d, 0xce,
	0x2d, 0x74, 0xd1, 0x5f, 0xa2, 0xed, 0x4e, 0xd1, 0x8b, 0x5e, 0xd1, 0xc2, 0xb7, 0x08, 0x65, 0x68,
	0xfe, 0x14, 0xa0, 0xb2, 0xf1, 0xcc, 0x08, 0xf4, 0x01, 0x77, 0x88, 0x01, 0xc7, 0x03, 0xee, 0x8c,
	0x46, 0xfd, 0x9e, 0xa1, 0xd5, 0xb5, 0x56, 0xd5, 0xda, 0xc8, 0xb4, 0x32, 0x5c, 0x2d, 0xd0, 0x28,
	0x6c, 0x2b, 0x4a, 0x12, 0x13, 0x2a, 0x43, 0x26, 0x67, 0xb6, 0xbf, 0x46, 0x43, 0xaf, 0x6b, 0xad,
	0x92, 0xb5, 0xd5, 0xe4, 0x1a, 0x40, 0x9d, 0x1f, 0xa2, 0xb9, 0x83, 0xc2, 0x28, 0xc6, 0xd5, 0x8c,
	0x63, 0x7e, 0x6b, 0x50, 0x7e, 0xe2, 0x62, 0x86, 0x42, 0xb5, 0xbe, 0xc7, 0xa7, 0xcc, 0xeb, 0x19,
	0x47, 0xd5, 0x3d, 0x54, 0x3b, 0x65, 0x18, 0x32, 0x0e, 0x19, 0x42, 0x29, 0x64, 0x72, 0x26, 0x0d,
	0xbd, 0xae, 0xb7, 0x4e, 0x3a, 0xf7, 0x34, 0x17, 0x06, 0xfd, 0x3f, 0x08, 0xba, 0xd1, 0x34, 0x21,
	0xa1, 0x8a, 0xcf, 0x4a, 0x2e, 0x33, 0xc7, 0x50, 0x54, 0x72, 0x4f, 0x30, 0x57, 0x50, 0x55, 0x1d,
	0xfd, 0xc0, 0xc3, 0x8f, 0x18, 0xab, 0x64, 0xed, 0x8c, 0x7d, 0xe1, 0x34, 0x2e, 0xe1, 0x22, 0x47,
	0x24, 0x17, 0x3c, 0x90, 0xd8, 0xf9, 0x84, 0x5a, 0x8f, 0x85, 0xcc, 0x8e, 0xf1, 0xed, 0x04, 0x9f,
	0xbc, 0xc0, 0xe9, 0x9f, 0x7e, 0x72, 0x73, 0xf0, 0x96, 0xe6, 0xed, 0x21, 0xad, 0xc9, 0xf3, 0x8d,
	0xa3, 0x2e, 0x42, 0xd3, 0xe5, 0x73, 0x3a, 0xf1, 0xc3, 0x69, 0xe4, 0x50, 0x64, 0x13, 0xc1, 0x9e,
	0xa9, 0x5c, 0x05, 0xee, 0x54, 0xf0, 0xc0, 0x5f, 0xa3, 0xa0, 0xe9, 0x1d, 0xdd, 0x3c, 0xe8, 0xa3,
	0x36, 0x6e, 0xa6, 0x83, 0x2e, 0x9f, 0xb7, 0x93, 0xe1, 0x76, 0x76, 0xb8, 0x9d, 0x0e, 0x3b, 0xe5,
	0xf8, 0xc7, 0xbd, 0xfb, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x12, 0x98, 0x50, 0x52, 0xcc, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DataServerServiceClient is the client API for DataServerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DataServerServiceClient interface {
	ReceiveSchedule(ctx context.Context, in *ReceiveScheduleRequest, opts ...grpc.CallOption) (*ReceiveScheduleResponse, error)
}

type dataServerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataServerServiceClient(cc grpc.ClientConnInterface) DataServerServiceClient {
	return &dataServerServiceClient{cc}
}

func (c *dataServerServiceClient) ReceiveSchedule(ctx context.Context, in *ReceiveScheduleRequest, opts ...grpc.CallOption) (*ReceiveScheduleResponse, error) {
	out := new(ReceiveScheduleResponse)
	err := c.cc.Invoke(ctx, "/dataserverservice.DataServerService/ReceiveSchedule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataServerServiceServer is the server API for DataServerService service.
type DataServerServiceServer interface {
	ReceiveSchedule(context.Context, *ReceiveScheduleRequest) (*ReceiveScheduleResponse, error)
}

// UnimplementedDataServerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDataServerServiceServer struct {
}

func (*UnimplementedDataServerServiceServer) ReceiveSchedule(ctx context.Context, req *ReceiveScheduleRequest) (*ReceiveScheduleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceiveSchedule not implemented")
}

func RegisterDataServerServiceServer(s *grpc.Server, srv DataServerServiceServer) {
	s.RegisterService(&_DataServerService_serviceDesc, srv)
}

func _DataServerService_ReceiveSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReceiveScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServerServiceServer).ReceiveSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dataserverservice.DataServerService/ReceiveSchedule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServerServiceServer).ReceiveSchedule(ctx, req.(*ReceiveScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DataServerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dataserverservice.DataServerService",
	HandlerType: (*DataServerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReceiveSchedule",
			Handler:    _DataServerService_ReceiveSchedule_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dataserver.proto",
}
