// Code generated by protoc-gen-go. DO NOT EDIT.
// source: selector.proto

package service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Coordinator asks for all or specific number of workers
type WorkersRequest struct {
	All                  bool     `protobuf:"varint,1,opt,name=all,proto3" json:"all,omitempty"`
	Number               int32    `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorkersRequest) Reset()         { *m = WorkersRequest{} }
func (m *WorkersRequest) String() string { return proto.CompactTextString(m) }
func (*WorkersRequest) ProtoMessage()    {}
func (*WorkersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4729c7385e2dd96, []int{0}
}

func (m *WorkersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkersRequest.Unmarshal(m, b)
}
func (m *WorkersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkersRequest.Marshal(b, m, deterministic)
}
func (m *WorkersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkersRequest.Merge(m, src)
}
func (m *WorkersRequest) XXX_Size() int {
	return xxx_messageInfo_WorkersRequest.Size(m)
}
func (m *WorkersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WorkersRequest proto.InternalMessageInfo

func (m *WorkersRequest) GetAll() bool {
	if m != nil {
		return m.All
	}
	return false
}

func (m *WorkersRequest) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

// Selector responds with a list of available workers
type WorkersResponse struct {
	Workers              []*WorkersResponse_Worker `protobuf:"bytes,1,rep,name=workers,proto3" json:"workers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *WorkersResponse) Reset()         { *m = WorkersResponse{} }
func (m *WorkersResponse) String() string { return proto.CompactTextString(m) }
func (*WorkersResponse) ProtoMessage()    {}
func (*WorkersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4729c7385e2dd96, []int{1}
}

func (m *WorkersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkersResponse.Unmarshal(m, b)
}
func (m *WorkersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkersResponse.Marshal(b, m, deterministic)
}
func (m *WorkersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkersResponse.Merge(m, src)
}
func (m *WorkersResponse) XXX_Size() int {
	return xxx_messageInfo_WorkersResponse.Size(m)
}
func (m *WorkersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WorkersResponse proto.InternalMessageInfo

func (m *WorkersResponse) GetWorkers() []*WorkersResponse_Worker {
	if m != nil {
		return m.Workers
	}
	return nil
}

type WorkersResponse_Worker struct {
	WorkerUUID           string   `protobuf:"bytes,1,opt,name=workerUUID,proto3" json:"workerUUID,omitempty"`
	DeviceType           string   `protobuf:"bytes,2,opt,name=deviceType,proto3" json:"deviceType,omitempty"`
	ChurnProbability     float32  `protobuf:"fixed32,3,opt,name=churnProbability,proto3" json:"churnProbability,omitempty"`
	Flops                int32    `protobuf:"varint,4,opt,name=flops,proto3" json:"flops,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorkersResponse_Worker) Reset()         { *m = WorkersResponse_Worker{} }
func (m *WorkersResponse_Worker) String() string { return proto.CompactTextString(m) }
func (*WorkersResponse_Worker) ProtoMessage()    {}
func (*WorkersResponse_Worker) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4729c7385e2dd96, []int{1, 0}
}

func (m *WorkersResponse_Worker) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkersResponse_Worker.Unmarshal(m, b)
}
func (m *WorkersResponse_Worker) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkersResponse_Worker.Marshal(b, m, deterministic)
}
func (m *WorkersResponse_Worker) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkersResponse_Worker.Merge(m, src)
}
func (m *WorkersResponse_Worker) XXX_Size() int {
	return xxx_messageInfo_WorkersResponse_Worker.Size(m)
}
func (m *WorkersResponse_Worker) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkersResponse_Worker.DiscardUnknown(m)
}

var xxx_messageInfo_WorkersResponse_Worker proto.InternalMessageInfo

func (m *WorkersResponse_Worker) GetWorkerUUID() string {
	if m != nil {
		return m.WorkerUUID
	}
	return ""
}

func (m *WorkersResponse_Worker) GetDeviceType() string {
	if m != nil {
		return m.DeviceType
	}
	return ""
}

func (m *WorkersResponse_Worker) GetChurnProbability() float32 {
	if m != nil {
		return m.ChurnProbability
	}
	return 0
}

func (m *WorkersResponse_Worker) GetFlops() int32 {
	if m != nil {
		return m.Flops
	}
	return 0
}

// Coordinator sends a list of assignments to selector
type HandoffRequest struct {
	Assignments          []*HandoffRequest_Assignment `protobuf:"bytes,1,rep,name=assignments,proto3" json:"assignments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *HandoffRequest) Reset()         { *m = HandoffRequest{} }
func (m *HandoffRequest) String() string { return proto.CompactTextString(m) }
func (*HandoffRequest) ProtoMessage()    {}
func (*HandoffRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4729c7385e2dd96, []int{2}
}

func (m *HandoffRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandoffRequest.Unmarshal(m, b)
}
func (m *HandoffRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandoffRequest.Marshal(b, m, deterministic)
}
func (m *HandoffRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandoffRequest.Merge(m, src)
}
func (m *HandoffRequest) XXX_Size() int {
	return xxx_messageInfo_HandoffRequest.Size(m)
}
func (m *HandoffRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HandoffRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HandoffRequest proto.InternalMessageInfo

func (m *HandoffRequest) GetAssignments() []*HandoffRequest_Assignment {
	if m != nil {
		return m.Assignments
	}
	return nil
}

type HandoffRequest_Assignment struct {
	WorkerUUID           string   `protobuf:"bytes,1,opt,name=workerUUID,proto3" json:"workerUUID,omitempty"`
	TaskUUID             string   `protobuf:"bytes,2,opt,name=taskUUID,proto3" json:"taskUUID,omitempty"`
	DataServerID         string   `protobuf:"bytes,3,opt,name=dataServerID,proto3" json:"dataServerID,omitempty"`
	AggregatorID         string   `protobuf:"bytes,4,opt,name=aggregatorID,proto3" json:"aggregatorID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandoffRequest_Assignment) Reset()         { *m = HandoffRequest_Assignment{} }
func (m *HandoffRequest_Assignment) String() string { return proto.CompactTextString(m) }
func (*HandoffRequest_Assignment) ProtoMessage()    {}
func (*HandoffRequest_Assignment) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4729c7385e2dd96, []int{2, 0}
}

func (m *HandoffRequest_Assignment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandoffRequest_Assignment.Unmarshal(m, b)
}
func (m *HandoffRequest_Assignment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandoffRequest_Assignment.Marshal(b, m, deterministic)
}
func (m *HandoffRequest_Assignment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandoffRequest_Assignment.Merge(m, src)
}
func (m *HandoffRequest_Assignment) XXX_Size() int {
	return xxx_messageInfo_HandoffRequest_Assignment.Size(m)
}
func (m *HandoffRequest_Assignment) XXX_DiscardUnknown() {
	xxx_messageInfo_HandoffRequest_Assignment.DiscardUnknown(m)
}

var xxx_messageInfo_HandoffRequest_Assignment proto.InternalMessageInfo

func (m *HandoffRequest_Assignment) GetWorkerUUID() string {
	if m != nil {
		return m.WorkerUUID
	}
	return ""
}

func (m *HandoffRequest_Assignment) GetTaskUUID() string {
	if m != nil {
		return m.TaskUUID
	}
	return ""
}

func (m *HandoffRequest_Assignment) GetDataServerID() string {
	if m != nil {
		return m.DataServerID
	}
	return ""
}

func (m *HandoffRequest_Assignment) GetAggregatorID() string {
	if m != nil {
		return m.AggregatorID
	}
	return ""
}

// Empty for now
type HandoffResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandoffResponse) Reset()         { *m = HandoffResponse{} }
func (m *HandoffResponse) String() string { return proto.CompactTextString(m) }
func (*HandoffResponse) ProtoMessage()    {}
func (*HandoffResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4729c7385e2dd96, []int{3}
}

func (m *HandoffResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandoffResponse.Unmarshal(m, b)
}
func (m *HandoffResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandoffResponse.Marshal(b, m, deterministic)
}
func (m *HandoffResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandoffResponse.Merge(m, src)
}
func (m *HandoffResponse) XXX_Size() int {
	return xxx_messageInfo_HandoffResponse.Size(m)
}
func (m *HandoffResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HandoffResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HandoffResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*WorkersRequest)(nil), "selectorservice.WorkersRequest")
	proto.RegisterType((*WorkersResponse)(nil), "selectorservice.WorkersResponse")
	proto.RegisterType((*WorkersResponse_Worker)(nil), "selectorservice.WorkersResponse.Worker")
	proto.RegisterType((*HandoffRequest)(nil), "selectorservice.HandoffRequest")
	proto.RegisterType((*HandoffRequest_Assignment)(nil), "selectorservice.HandoffRequest.Assignment")
	proto.RegisterType((*HandoffResponse)(nil), "selectorservice.HandoffResponse")
}

func init() {
	proto.RegisterFile("selector.proto", fileDescriptor_e4729c7385e2dd96)
}

var fileDescriptor_e4729c7385e2dd96 = []byte{
	// 435 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0xbb, 0x4d, 0x9b, 0x26, 0x53, 0x94, 0x94, 0x15, 0x42, 0x56, 0x0e, 0x60, 0xf9, 0x50,
	0xa2, 0x1e, 0x36, 0x52, 0xb9, 0x71, 0x6b, 0x55, 0x09, 0x2a, 0x21, 0x54, 0x36, 0x54, 0x48, 0xdc,
	0xd6, 0xce, 0xc4, 0xb1, 0xea, 0xec, 0x86, 0xdd, 0x75, 0x51, 0x78, 0x04, 0x4e, 0xbc, 0x08, 0x0f,
	0xc5, 0x23, 0xf0, 0x06, 0xc8, 0xde, 0xb5, 0x71, 0xd2, 0xa2, 0xdc, 0x3c, 0xff, 0xcc, 0x37, 0x3b,
	0xff, 0x8e, 0x17, 0x06, 0x06, 0x73, 0x4c, 0xac, 0xd2, 0x6c, 0xa5, 0x95, 0x55, 0x74, 0x58, 0xc7,
	0x06, 0xf5, 0x7d, 0x96, 0x60, 0xf4, 0x06, 0x06, 0x9f, 0x95, 0xbe, 0x43, 0x6d, 0x38, 0x7e, 0x2d,
	0xd0, 0x58, 0x7a, 0x02, 0x1d, 0x91, 0xe7, 0x01, 0x09, 0xc9, 0xb8, 0xc7, 0xcb, 0x4f, 0xfa, 0x1c,
	0xba, 0xb2, 0x58, 0xc6, 0xa8, 0x83, 0xfd, 0x90, 0x8c, 0x0f, 0xb9, 0x8f, 0xa2, 0xdf, 0x04, 0x86,
	0x0d, 0x6c, 0x56, 0x4a, 0x1a, 0xa4, 0x17, 0x70, 0xf4, 0xcd, 0x49, 0x01, 0x09, 0x3b, 0xe3, 0xe3,
	0xf3, 0x57, 0x6c, 0xeb, 0x48, 0xb6, 0x85, 0xf8, 0x98, 0xd7, 0xdc, 0xe8, 0x07, 0x81, 0xae, 0xd3,
	0xe8, 0x0b, 0x00, 0xa7, 0xde, 0xde, 0x5e, 0x5f, 0x55, 0x23, 0xf5, 0x79, 0x4b, 0x29, 0xf3, 0x33,
	0x2c, 0x9b, 0x7e, 0x5a, 0xaf, 0xb0, 0x9a, 0xae, 0xcf, 0x5b, 0x0a, 0x3d, 0x83, 0x93, 0x64, 0x51,
	0x68, 0x79, 0xa3, 0x55, 0x2c, 0xe2, 0x2c, 0xcf, 0xec, 0x3a, 0xe8, 0x84, 0x64, 0xbc, 0xcf, 0x1f,
	0xe8, 0xf4, 0x19, 0x1c, 0xce, 0x73, 0xb5, 0x32, 0xc1, 0x41, 0x65, 0xd2, 0x05, 0xd1, 0x1f, 0x02,
	0x83, 0x77, 0x42, 0xce, 0xd4, 0x7c, 0x5e, 0x5f, 0xd0, 0x7b, 0x38, 0x16, 0xc6, 0x64, 0xa9, 0x5c,
	0xa2, 0xb4, 0xb5, 0xcd, 0xb3, 0x07, 0x36, 0x37, 0x29, 0x76, 0xd1, 0x20, 0xbc, 0x8d, 0x8f, 0x7e,
	0x12, 0x80, 0x7f, 0xb9, 0x9d, 0x8e, 0x47, 0xd0, 0xb3, 0xc2, 0xdc, 0x55, 0x59, 0xe7, 0xb7, 0x89,
	0x69, 0x04, 0x4f, 0x66, 0xc2, 0x8a, 0x29, 0xea, 0x7b, 0xd4, 0xd7, 0x57, 0x95, 0xd3, 0x3e, 0xdf,
	0xd0, 0xca, 0x1a, 0x91, 0xa6, 0x1a, 0x53, 0x61, 0x55, 0x59, 0x73, 0xe0, 0x6a, 0xda, 0x5a, 0xf4,
	0x14, 0x86, 0xcd, 0xf0, 0x6e, 0x47, 0xe7, 0xbf, 0x08, 0xf4, 0xa6, 0xde, 0x20, 0xfd, 0x08, 0xf0,
	0x16, 0xad, 0x5f, 0x23, 0x7d, 0xf9, 0xff, 0x05, 0x57, 0xce, 0x47, 0xe1, 0xae, 0x3f, 0x20, 0xda,
	0xa3, 0x1f, 0xe0, 0xc8, 0x1f, 0xf9, 0x48, 0xbf, 0xcd, 0x9b, 0x7c, 0xa4, 0xdf, 0xd6, 0xb4, 0xd1,
	0xde, 0x65, 0x02, 0xa7, 0x89, 0x5a, 0xb2, 0x34, 0xb3, 0x8b, 0x22, 0x66, 0x28, 0x52, 0x2d, 0xe6,
	0xcc, 0xac, 0x65, 0xb2, 0xd0, 0x4a, 0x66, 0xdf, 0x51, 0x33, 0xcf, 0x5e, 0x0e, 0x6b, 0x5b, 0x53,
	0x27, 0xdc, 0x90, 0x2f, 0xa7, 0x1e, 0x4b, 0xd4, 0x72, 0xe2, 0xd0, 0x49, 0x1b, 0x9d, 0x78, 0x34,
	0xee, 0x56, 0x6f, 0xea, 0xf5, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3c, 0xc1, 0xdf, 0x5d, 0x65,
	0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SelectorClient is the client API for Selector service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SelectorClient interface {
	GetWorkers(ctx context.Context, in *WorkersRequest, opts ...grpc.CallOption) (*WorkersResponse, error)
	Handoff(ctx context.Context, in *HandoffRequest, opts ...grpc.CallOption) (*HandoffResponse, error)
}

type selectorClient struct {
	cc grpc.ClientConnInterface
}

func NewSelectorClient(cc grpc.ClientConnInterface) SelectorClient {
	return &selectorClient{cc}
}

func (c *selectorClient) GetWorkers(ctx context.Context, in *WorkersRequest, opts ...grpc.CallOption) (*WorkersResponse, error) {
	out := new(WorkersResponse)
	err := c.cc.Invoke(ctx, "/selectorservice.Selector/GetWorkers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *selectorClient) Handoff(ctx context.Context, in *HandoffRequest, opts ...grpc.CallOption) (*HandoffResponse, error) {
	out := new(HandoffResponse)
	err := c.cc.Invoke(ctx, "/selectorservice.Selector/Handoff", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SelectorServer is the server API for Selector service.
type SelectorServer interface {
	GetWorkers(context.Context, *WorkersRequest) (*WorkersResponse, error)
	Handoff(context.Context, *HandoffRequest) (*HandoffResponse, error)
}

// UnimplementedSelectorServer can be embedded to have forward compatible implementations.
type UnimplementedSelectorServer struct {
}

func (*UnimplementedSelectorServer) GetWorkers(ctx context.Context, req *WorkersRequest) (*WorkersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWorkers not implemented")
}
func (*UnimplementedSelectorServer) Handoff(ctx context.Context, req *HandoffRequest) (*HandoffResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Handoff not implemented")
}

func RegisterSelectorServer(s *grpc.Server, srv SelectorServer) {
	s.RegisterService(&_Selector_serviceDesc, srv)
}

func _Selector_GetWorkers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SelectorServer).GetWorkers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/selectorservice.Selector/GetWorkers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SelectorServer).GetWorkers(ctx, req.(*WorkersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Selector_Handoff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandoffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SelectorServer).Handoff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/selectorservice.Selector/Handoff",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SelectorServer).Handoff(ctx, req.(*HandoffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Selector_serviceDesc = grpc.ServiceDesc{
	ServiceName: "selectorservice.Selector",
	HandlerType: (*SelectorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWorkers",
			Handler:    _Selector_GetWorkers_Handler,
		},
		{
			MethodName: "Handoff",
			Handler:    _Selector_Handoff_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "selector.proto",
}
